[mqtt]
host = "mqtt.example.com"
port = 1883
topic = "owntracks/+/+"
user = "mqttuser"
password = "mqttpassword"
tls = false
anonymous = false

[hauk]
host = "hauk.example.com"
port = 443
tls = true
duration = 3600 # 1 hour
interval = 1    # 1 second
user = ""
password = ""

[mapper]
start_session_auto = true
stop_session_auto = true
start_session_manual = true

[notification.smtp]
enabled = true
smtp_host = "mail"
smtp_port = 25
from = "noreply@example.com"
to = "dude@example.com"

[notification.gotify]
enabled = false
url = "http://gotify"
app_token = "token"
priority = 5
